AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda collection
Globals:
  Function:
    Timeout: 900
Outputs:
  CrawlRssFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CrawlRssFunction
      - Arn
  CrawlRssFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - CrawlRssFunctionRole
      - Arn
Resources:
  CrawlRssFunction:
    Properties:
      CodeUri: s3://12bitlambdafns/6679fc5e524fe2ad9ea0cff12131ebf0
      Environment:
        Variables:
          GITHUB_ACCESS_TOKEN: 8a6bd05d00472d5b03beed8b6554fb53cdf565a9
      Events:
        Schedule:
          Properties:
            Schedule: cron(0 6,18 * * ? *)
          Type: Schedule
      Handler: crawl-rss
      Runtime: go1.x
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
