AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda collection
Globals:
  Function:
    Timeout: 300
Outputs:
  CrawlRssAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/crawl-rss/
  CrawlRssFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CrawlRssFunction
      - Arn
  CrawlRssFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - CrawlRssFunctionRole
      - Arn
Resources:
  CrawlRssFunction:
    Properties:
      CodeUri: s3://12bitlambdafns/ccdc8106f44d1d8a7f6fd1775c881452
      Environment:
        Variables:
          GITHUB_ACCESS_TOKEN: 2546d5c680321a69390f7b4af2b84dcf1612ab93
      Events:
        API:
          Properties:
            Method: GET
            Path: /crawl-rss
          Type: Api
        Schedule:
          Properties:
            Schedule: rate(1 day)
          Type: Schedule
      Handler: crawl-rss
      Runtime: go1.x
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
