AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda collection
Globals:
  Function:
    Timeout: 900
Outputs:
  CrawlRssFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CrawlRssFunction
      - Arn
  CrawlRssFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - CrawlRssFunctionRole
      - Arn
Resources:
  CrawlRssFunction:
    Properties:
      CodeUri: s3://12bitlambdafns/44e7e67c6146c9c5c56387447c5d85e1
      Environment:
        Variables:
          GITHUB_ACCESS_TOKEN: d82f360477b3bdd8282701846d867acd8d8c61d2
      Events:
        Schedule:
          Properties:
            Schedule: cron(0 6,18 * * ? *)
          Type: Schedule
      Handler: crawl-rss
      Runtime: go1.x
      Tracing: Active
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
