AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda collection

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  CrawlRssFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: crawl-rss/
      Handler: crawl-rss
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 6,18 * * ? *)
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          GITHUB_ACCESS_TOKEN: d82f360477b3bdd8282701846d867acd8d8c61d2

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CrawlRssFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt CrawlRssFunction.Arn
  CrawlRssFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CrawlRssFunctionRole.Arn
